server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

<<<<<<< HEAD
    resolver 127.0.0.11 valid=30s;

    location /api/v1/ventas {
        set $upstream_ventas http://ms-ventas:8082;
        proxy_pass $upstream_ventas;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/despachos {
        set $upstream_despacho http://ms-despacho:8081;
        proxy_pass $upstream_despacho;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
=======
    location /api/v1/ventas {
        proxy_pass http://ms-ventas:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/despachos {
        proxy_pass http://ms-despacho:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
>>>>>>> origin/deploy
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
