#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${DESPACHO_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${DESPACHO_DB_USER}'@'%' IDENTIFIED BY '${DESPACHO_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${DESPACHO_DB_NAME}\`.* TO '${DESPACHO_DB_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS \`${VENTAS_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${VENTAS_DB_USER}'@'%' IDENTIFIED BY '${VENTAS_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${VENTAS_DB_NAME}\`.* TO '${VENTAS_DB_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL
